[package]
name = "i3-focus-last"
version = "0.3.1"
authors = ["lbonn"]
description = "Focus last window on i3"
license = "MIT"
repository = "https://github.com/lbonn/i3-focus-last"
edition = "2018"

[dependencies]
i3ipc = "0.10.0"
xcb = "0.9.0"
